package treeGenerator;
 /**
  * Data structure for attributes generated by the tree.
  * @author root
  *
  */

public class Attribute 
{
	private boolean observable;
	private boolean isBool;
	private String attributeName;
	private int length;
	private String[] setValues;
	
	public Attribute(boolean o, boolean b, String name, int s)
	{
		this.setObservable(o);
		this.setBool(b);
		this.setAttributeName(name);
		this.setLength(s);
	}


	
	public int getLength() {
		return length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	public void setObservable(boolean observable) {
		this.observable = observable;
	}

	public boolean isObservable() {
		return observable;
	}

	public void setBool(boolean isBool) {
		this.isBool = isBool;
	}

	public boolean isBool() {
		return isBool;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getAttributeName() {
		return attributeName;
	}
	
	public String toString()
	{
		
		String myOut = "@attribute "+this.getAttributeName()+" ";
		if(this.isObservable())
		{
			myOut = myOut+"observable ";
		}
		if(this.isBool)
		{
			myOut = myOut+"boolean ";
		}
		else
		{
			if(this.setValues.length==0)
			{
				myOut = myOut+"{ ";
				for(int i = 0; this.getLength() >i; i++)
				{
					myOut = myOut+" "+i+" ";
				}
				myOut = myOut+" }";
			}
			else
			{
				myOut = myOut+"{ ";
				for(int i = 0; this.getLength() >i; i++)
				{
					myOut = myOut+" "+this.setValues[i]+" ";
				}
				myOut = myOut+" }";
			}
		}
		
		return myOut;
	}



	public void setSetValues(String[] setValues) {
		this.setValues = setValues;
	}



	public String[] getSetValues() {
		return setValues;
	}
	
}
