package treeGenerator;
/*
 * Data Structure for Goals generated by the tree.
 */

public class Goal implements TreeGenElement
{
	private String IDNumber;
	//private String type;
	private int depth;
	
	public Goal()
	{
		this.setIDNumber("");
		this.setDepth(0);
	}
	
	public Goal(String number)
	{
		this.setIDNumber(number);
		this.setDepth(0);
	}

	public Goal(int number)
	{
		this.setIDNumber(""+number);
		this.setDepth(0);
	}
	
	public void setIDNumber(String iDNumber) 
	{
		IDNumber = iDNumber;
	}
	
	
	public String getIDNumber() 
	{
		return IDNumber;
	}
	
	/*public void setType(String type) {
		this.type = type;
	}
	public String getType() {
		return type;
	}*/
	
	public String toString()
	{
		if(depth==0)
		{
			return "@topgoal "+this.getIDNumber();
		}
		return "@goal G"+this.getIDNumber();
	}

	public String toNameString()
	{
		if(depth==0)
		{
			return this.getIDNumber();
		}
		return "G"+this.getIDNumber();
	}
	
	public void setDepth(int depth) {
		this.depth = depth;
	}

	public int getDepth() {
		return depth;
	}
	
	public boolean equal(Object o)
	{
		if (o instanceof Goal)
		{
			Goal compareTo = (Goal)o;
			if(compareTo.getIDNumber().equals(this.getIDNumber()))
			{
				return true;
			}
		}
		return false;
	}
}
