package expGenerator;

/**
 * This class was created to be able to add goals and plans in a goal-plan tree.
 * All goals and plans have an id, which is unique and fixed by the user
 * and an index, which is generated by the simulator 
 * @author stephane
 *
 */
public class GoalPlan {
	/** id of the goal or plan specified by the user */
	String id;
	/** an index of the goal or plan that is specified by the simulator, the 
	 * index is used to access the goal or plan easily
	 */
	int index;
	
	/**
	 * Default constructor where the user inputs the name of the goal or plan
	 * @param myid name/id of the goal or plan
	 */
	public GoalPlan(String myid){id = myid;}
	
	/** get the string representing the id of the goal/plan 
	 * @return the id of the goal/plan
	 */
	public String getId() {
		return id;
	}
	/** reset the id of the goal/plan 
	 * @param id id of the goal/plan*/
	public void setId(String id) {
		this.id = id;
	}
	/** 
	 * method that simply returns the id of the goal/plan
	 */
	public String toString(){return id;}
	
}
